jdbc:
  jdbc-url: jdbc:mysql://10.4.242.114:5001/hermes_item?useUnicode=true&amp;connectTimeout=1000&amp;socketTimeout=3000&amp;characterEncoding=UTF-8
---
spring:
  profiles: online
  data:
    elasticsearch:
      cluster-nodes: 13.94.43.42:9300
jdbc:
  jdbc-url: jdbc:mysql://13.94.43.42:5001/hermes_item?useUnicode=true&amp;connectTimeout=1000&amp;socketTimeout=3000&amp;characterEncoding=UTF-8
  jdbc-password: 5781245Hu
